### PR TITLE
add basic man page - fixes #17

### LINKED ISSUE #17: No manpage
There's no manpage and it would probably be useful to include one.

### PR DESCRIPTION
**Pull request by 01micko**
This can be added to later as it just has the basics.

### CODE REVIEW

**Comment by johanmalm** [comment]
Thanks. Good idea.
I'd prefer the man page in `.scd` format like we've done in `labwc` itself.
Fancy doing the conversion?

**Comment by 01micko** [comment]
Sure. Just have to add scdoc build time dependency. I did consider that but thought the extra dep may have been unwanted.
Do you have anything to add @johanmalm to the page?
Won't be until this evening AEST time.

**Comment by 01micko** [comment]
Had to recall a bit of `meson` fu :)

Should be ready for merge.

**Comment by johanmalm** [comment]
Thanks. Great effort.
Can expand on content later.

**Comment by 01micko** [comment]
Thanks :)

**Pull request merged**
